# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - '**'

env:
  project-directory: ./
  node-version: '18'

jobs:
  client:
    name: Build Client Project
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip-ci')
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
      - name: npm clean install
        run: npm ci --legacy-peer-deps
        working-directory: ${{ env.project-directory }}
      - name: run ESLint
        run: npm run lint
        working-directory: ${{ env.project-directory }}
      - name: build client dev project
        if: github.event_name == 'push' && github.repository == 'Greenstand/treetracker-admin-client'
        run: npm run build:dev
        working-directory: ${{ env.project-directory }}
      - uses: actions/upload-artifact@v2
        if: github.event_name == 'push' && github.repository == 'Greenstand/treetracker-admin-client'
        with:
          name: client-bundle
          path: build-dev
      - name: build client project
        run: npm run build
        working-directory: ${{ env.project-directory }}
      - name: run React tests
        run: npm test
        working-directory: ${{ env.project-directory }}
