name: Deploy to Production Environment

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'git-tag'
        required: true

env:
  project-directory: ./
  node-version: '18'

jobs:
  client:
    name: Build Client Project
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip-ci')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
      - name: npm clean install
        run: npm ci --legacy-peer-deps
        working-directory: ${{ env.project-directory }}
      - name: build client project
        run: CI= REACT_APP_WEBMAP_DOMAIN=https://map.treetracker.org REACT_APP_API_ROOT=https://prod-k8s.treetracker.org/api/admin npm run build
        working-directory: ${{ env.project-directory }}
      - uses: actions/upload-artifact@v2
        with:
          name: client-bundle
          path: build

  deploy:
    name: Deploy to CDN
    runs-on: ubuntu-latest
    needs: client
    if: |
      github.repository == 'Greenstand/treetracker-admin-client'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Download bundled client resources
        uses: actions/download-artifact@v2
        with:
          name: client-bundle
          path: build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
      - name: Copy front end resources to s3 bucket
        run: |
          aws s3 sync build s3://${{ secrets.PROD_CDN_S3_BUCKET }} --delete
      - name: Invalidate cloudfront caches
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.PROD_CDN_DISTRIBUTION_ID }} --paths "/*"
